version: "3.7"

services:
  kind-manager:
    build: .
    container_name: kind-manager
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kind-config.yaml:/kind-config.yaml
      - ./scripts:/scripts
      - ./kubeconfig:/root/.kube/config
    entrypoint: /bin/sh -c "/scripts/start-kind.sh && tail -f /dev/null"
